name: OIG
favicon: null
layout_spectrum: 0.46922586602158844
typography_spectrum: 0.1865598785225302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.03125653835013509
  lightness: 0.08327234187163413
  saturation: 0.5504776746965945
  rhythmicContrast: 0.8725254514720291
purpose: []
